src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="json")
     */
    private $usersid = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $machinesid = [];

    /**
     * @ORM\Column(type="date")
     */
    private $dateStart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateEnd;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $frequence;

    /**
     * @ORM\Column(type="boolean")
     */
    private $valid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUsersid(): ?array
    {
        return $this->usersid;
    }

    public function setUsersid(array $usersid): self
    {
        $this->usersid = $usersid;

        return $this;
    }

    public function getMachinesid(): ?array
    {
        return $this->machinesid;
    }

    public function setMachinesid(?array $machinesid): self
    {
        $this->machinesid = $machinesid;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->dateEnd;
    }

    public function setDateEnd(?\DateTimeInterface $dateEnd): self
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    public function getFrequence(): ?string
    {
        return $this->frequence;
    }

    public function setFrequence(?string $frequence): self
    {
        $this->frequence = $frequence;

        return $this;
    }

    public function getValid(): ?bool
    {
        return $this->valid;
    }

    public function setValid(bool $valid): self
    {
        $this->valid = $valid;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface /*, EquatableInterface*/
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;
    
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];
    
    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $datecreation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetPassword;
    
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getEmail(): ?string
    {
        return $this->email;
    }
    
    public function setEmail(string $email): self
    {
        $this->email = $email;
        
        return $this;
    }
    
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }
    
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_NOUVEAU
        $roles[] = 'ROLE_NOUVEAU';
        
        return array_unique($roles);
    }
    
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        
        return $this;
    }
    
    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }
    
    public function setPassword(string $password): self
    {
        $this->password = $password;
        
        return $this;
    }
    
    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }
    
    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    
    public function getNom(): ?string
    {
        return $this->Nom;
    }
    
    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;
        
        return $this;
    }
    
    public function getPrenom(): ?string
    {
        return $this->prenom;
    }
    
    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;
        
        return $this;
    }
    
    public function getDatecreation(): ?\DateTimeInterface
    {
        return $this->datecreation;
    }
    
    public function setDatecreation(?\DateTimeInterface $datecreation): self
    {
        $this->datecreation = $datecreation;
        
        return $this;
    }

    public function getResetPassword(): ?string
    {
        return $this->resetPassword;
    }

    public function setResetPassword(?string $resetPassword): self
    {
        $this->resetPassword = $resetPassword;

        return $this;
    }
    
}

templates/event/editEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <div class="row BorderJaune " style="margin-top:20px;">
    	<div class="col-12 offset-md-3 col-md-6 BorderRouge TitlePage">
    		<h1>Modifier l'événement : {{ event.title }}</h1>
    	</div>
    </div>
    <div class="row">
    	{{ form_start(form) }}
    		{{ form_row(form) }}
    		<button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
    	{{ form_end(form) }}
    </div>

		
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <div class="row BorderJaune " style="margin-top:20px;">
    	<div class="col-12 offset-md-3 col-md-6 BorderRouge TitlePage">
    		<h1>Événement</h1>
    	</div>
    </div>
    <div class="row">
    	<div class="col-12 offset-md-3 col-md-6 BorderVert">
    		<div class="row">
        		<div class="col-12 col-lg-6 BorderGris">
        			<a href="{{ path('event_noveau') }}">
        				<div class="BtnGros" style="margin-top:3px;">
            				<div class="textButtonCenter">
            					<i class="fas fa-calendar-plus"></i> Créer un événement
            				</div>
        				</div>
        			</a>
        		</div>
        		<div class="col-12 col-lg-6 BorderGris">
        			<a href="{{ path('event_searchListe') }}">
        				<div class="BtnGros" style="margin-top:3px;">
            				<div class="textButtonCenter">
            					<i class="far fa-list-alt"></i> Liste événements
            				</div>
        				</div>
        			</a>
        		</div>
    		</div>
    	</div>
    </div>
		
{% endblock %}

templates/event/infoEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info Event{% endblock %}
	
{% block body %}
	<div class="col-12 offset-md-3 col-md-6 BorderRouge TitlePage">
		<h1>Informations évenement</h1>
	</div>
	<div class="col-12 offset-md-3 col-md-6" style="border-bottom:1px solid #AAAAAA; margin-top:30px;margin-bottom:20px;">
	</div>
	<div class="row">
		<div class="col-12 offset-md-3 col-md-6">
			<div class="row">
        		<div class="col-6" style="padding-right:3px;">
        			<button class="btn btn-danger" onclick="ShowDeleteEvent();" style="float:right;color:white;cursor:pointer;"><i class="fas fa-trash-alt"></i> Supprimer l'événement</button>
        			<div id="confirmation" hidden>
        				<h3>Êtes vous sûr ?</h3>
        				<h4>Toute suppression est définitive... Il est absoluement impossible de revenir en arrière !</h4>
        				<a href="{{ path('event_delete',{id : event.id}) }}" >Oui, supprimer</a>
        			</div>
        		</div>
        		<div class="col-6" style="padding-left:3px;">
        			<a class="btn btn-secondary" style="color:#FFFFFF" href="{{ path('event_edit',{'id':event.id}) }}"><i class="far fa-edit"></i> Éditer l'événement</a>
        		</div>
			</div>
		</div>
	</div>
		<div class="col-12 offset-md-3 col-md-6" style="border-bottom:1px solid #AAAAAA; margin-top:20px;margin-bottom:10px;">
	</div>
	<div class="row BorderVert" style="margin-top:40px;">
		<div class="col-12">
    		<div class="row BorderJaune">
{#     			<div class="col-12">#}
        			<div class="offset-md-3 col-md-6">
                        <h3>Nom de l'évenement :</h3>
                        <div style="border-bottom:1px solid #AAAAAA;margin-bottom:8px"></div>
                        <div class="offset-1 col-10">
                            {{ event.title }}
            			</div>
    				<div style="margin-top:40px"></div>
{#     			</div>#}
    		</div>
    		</div>
    		<div class="row BorderJaune">
{#     			<div class="col-12">#}
    				<div class="offset-md-3 col-md-6">
            			<h3>Description de l'évenement :</h3>
                        <div style="border-bottom:1px solid #AAAAAA;margin-bottom:8px"></div>
            			<div class="offset-1 col-10">
            				{{ event.description }}
            			</div>
            			<div style="margin-top:40px"></div>	
{#         			</div>#}
    			</div>
    		</div>
    		<div class="row BorderJaune">
{#     			<div class="col-12">#}
    				<div class="offset-md-3 col-md-6">
        				<h3>Date de l'évenement (départ)</h3>
                    	<div style="border-bottom:1px solid #AAAAAA;margin-bottom:8px"></div>
        				<div class="offset-1 col-10">
        				    {{ event.dateStart|date("d/m/Y") }}
        				</div>
    					<div style="margin-top:40px"></div>
{#     				</div>#}
    			</div>
    	    </div>
    	    <div class="row BorderJaune">
    	    	<div class="col-12 offset-md-3 col-md-3 BorderBleu">
    				<h3>Liste des utilisateurs conviés</h3>
                	<div style="border-bottom:1px solid #AAAAAA;margin-bottom:8px"></div>
    				<div class="offset-1 col-10">
    				    {% if tableUser == null %}
    						Aucun Utilisateur</br>
    						<i class="fas fa-user-times" style="color:#EE8686; font-size:50px"></i>
    					{% endif %}
        				{% for user in tableUser %}
                            {% if user %}
            		    		<li class="listeUser">
            		    		<a href="{{ path('admin_UserControl_searchUser_id', {id: user.id}) }}" class="click" style="width:100%; height:100%;">
                		    		<div class="" name="listeUser" style="height:100%;">
                		    			<div class="elemListeUser userLogo" id="userLogo">
                		    			{% if "ROLE_ADMIN" in user.roles %}
            		    					<i class="fas fa-user-graduate" name="admin"></i>
            		    				 {% elseif "ROLE_USER" in user.roles%}
            		    				 	<i class="fas fa-user" name="user"></i>
            		    				 {% else %}
            		    				 	<i class="fas fa-user-lock" name="nouveau"></i>
            		    				 {% endif %} 		    				 
            		    				 </div>
            		               		<span><div class="elemListeUser userName" name="userName">{{ user.Nom }}</div>
            		               		<div class="elemListeUser userSurname">{{ user.prenom }}</div></span>
{#             		               		<div class="elemListeUser userEmail d-none d-md-inline-block">{{ user.email }} </div>#}
                		            	</br>
                		            </div>
            		            </a>
            		            </li>
            		        {% endif %}
        				{% endfor %}
        			</div>
    			</div>
    			<div class="col-12 col-md-3 BorderBleu">
    			<h3>Liste des machiness</h3>
                	<div style="border-bottom:1px solid #AAAAAA;margin-bottom:8px"></div>
    				<div class="offset-1 col-10">
    					{% if tableMachine == null %}
    						Aucune Machine</br>
    						<i class="far fa-folder-open" style="color:#EE8686; font-size:50px"></i>
    					{% endif %}
    					{% for machine in tableMachine%}
    						<a href="{{ path('modele3D', {'slug' : machine["maintenance"].id}) }}">
    						<div style="border:2px solid #00A1D7;border-radius:6px">
    							<img style="display:inline;height:60px; width:auto;" src="{{ asset('/image/modele/')~machine["modeleMachine"].id~('/')~machine["modeleMachine"].faceAvant }}">
    							<h3 style="display:inline">{{ machine["modeleMachine"].nom }}</h3>	
    							<h4 style="display:inline">{{ machine["machine"].name }}</h4>
    							<h5 style="display:inline">{{ machine["maintenance"].nom }}</h5>
    							<img style="display:inline;height:60px; width:auto;" src="{{ asset('image/modele/')~machine["maintenance"].modele.id~('/')~machine["maintenance"].id~('/')~machine["maintenance"].picturefilename }}">
    						</div>
    						</a>
    						</br>
    					{% endfor %}
    				</div>
    			</div>
    		</div>
    	</div>
	</div>
	<script src="{{ asset('bootstrap/Js/jquery.js') }}"></script>
	<script>
	console.log('script');
	function ShowDeleteEvent()
	{
		$('#confirmation').attr('hidden') ? $('#confirmation').removeAttr('hidden') : $('#confirmation').attr('hidden', true);
	}
	</script>
{% endblock %}

templates/event/listeEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Evenement{% endblock %}
	
{% block body %}
{# 	<meta http-equiv="refresh" content="600">#}
	<div class="col-12 offset-md-3 col-md-6 BorderRouge TitlePage">
		<h1>Rechercher un évenement</h1>
	</div>
	<div class="row">
		<div class="col-12 offset-md-4 col-md-4 BorderBleu">
			<div class="row displayRow BorderJaune">
			<div class="col-12">
			{{ form_start(form) }}
				<div class="offset-1 col-10 BorderVert">
	                {{ form_widget(form.Recherche,{'attr' : {'class' : 'form-control', 'placeholder' : 'Recherche'}}) }}
	            </div>
	        {{ form_end(form) }}
	        </div>
	        </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-12">
        <div class="row">
        	<div class="col-12 offset-md-2 col-md-8">
        		<ul>
                	{% for event in pagination %}
                		<a href="{{ path('event_Display', {id : event.id}) }}" class="btn-list-event">
                		<li class="EventListe" style="border: 1px solid #00A1D7; margin-top:5px;">
                    		<div>
                    		    <h2 style="display:inline; margin-left:15px;">{{ event.title }}</h2>&nbsp &nbsp &nbsp
                    		    <h4 style="display:inline; float:right; margin-right:15px;">{{ event.dateStart|date("d/m/Y") }}</h4>
                    		</div>
                		</li>
                		</a>
                	{% endfor %}
            	</ul>
            	</div>
        	</div>
        </div>
        <div class="col-12">
            <div class="row">
            	<div class="col-12 offset-md-2 col-md-8">
                	<nav aria-label="Page navigation example">
                        {{ knp_pagination_render(pagination) }}
                	</nav>
            	</div>
        	</div>
    	</div>
	</div>
{% endblock %}

templates/event/newEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EventController!{% endblock %}
	
{% block body %}
{# 	<meta http-equiv="refresh" content="600">#}
	<div class="col-12 offset-md-3 col-md-6 BorderRouge TitlePage">
		<h1>Ajouter un Évenement</h1>
	</div>
	<div class="col-12 offset-md-2 col-md-8" style="margin-top:20px">
        {{ form_start(formEvent) }}
        	<!-- =========================== I N F O R M A T I O N S ===================================== -->
        	<div style="border-bottom:1px solid #AAAAAA;">
        		<h3>Informations</h3>
        	</div>
        	<div style="margin-top:10px;" class="row">
        		<div class="offset-1 col-10">
        			<div class="row">
                        <div class="col-4">
                            {{ form_label(formEvent.title,'Nom de l\'évenement') }}
                        </div>
                        <div class="col-8">
                            {{ form_widget(formEvent.title, {'attr':{'placeholder' : "Titre de l'evenement", "class" : "form-control form-control-sm"}}) }}
                    	</div>
                        <div class="col-4">
                            {{ form_label(formEvent.description,'Description de l\'évenement') }}
                    	</div>
                        <div class="col-8">
                            {{ form_widget(formEvent.description, {'attr':{'placeholder' : "Description de l'evenement", "class" : "form-control form-control-sm"}}) }}
                   		</div>
               		</div>
           		</div>
           </div>
           <!-- ========================================================================================= -->
           <!-- =========================== U T I L I S A T E U R S ===================================== -->
           <div style="border-bottom:1px solid #AAAAAA; margin-top:20px;" class="row">
        		<h3 class="col-6">Utilisateurs</h3>
        		<h3 class="col-6">Machines</h3>
        	</div>
           	<div class="row" style="margin-top:20px;">
           		<div class="col-12 col-md-6 BorderBleu" style="margin-top:20px">
                	<ul class="listeUserId" id="listeUserId" data-prototype="{{ form_row(formEvent.usersid.vars.prototype)|e }}">
                	</ul>
                </div>
                <div class="col-12 col-md-6 BorderVert" style="border-left:1px solid #AAAAAA;">
                	<ul class="listeMachineId" data-prototype="{{ form_row(formEvent.machinesid.vars.prototype)|e }}">
                	</ul>  
                	<div class="offset-1">
                		<button type="button" class="add_tag_link btn btn-outline-primary" id="buttonAddMachine"><i class="fas fa-plus-circle"></i> Modèle</button>
                	</div>
                </div>
            </div>
            <!-- ========================================================================================= -->
           	<!-- =========================== U T I L I S A T E U R S ===================================== -->
           	<div style="border-bottom:1px solid #AAAAAA; margin-top:20px;" class="row">
        		<h3 class="col-6">Fréquence Répétition</h3>
        	</div>
        	<div id="Frequence" class="row" style="margin-top:10px;">
        		<div class="offset-1 col-10">
        			<div class="row">
{#         				<div class="col-4">#}
{#         		            {{ form_label(formEvent.frequence,'Fréquence de répétion') }}#}
{#         		        </div>#}
        		        <div class="col-12">
        		        	{{ form_widget(formEvent.frequence,{'attr' : {'class':'form-control form-control-sm','placeholder' : "Fréquence de répétition (0 si ponctuel)"}})}}
        		        </div>
{#         		        <div class="col-4">#}
{#         		            {{ form_label(formEvent.MesureTemps,'Mesure du temps') }}#}
{#         				</div>#}
        				<div class="col-12" style="margin-top:5px;">
        				    {{ form_widget(formEvent.MesureTemps,{'attr' : {'class':'form-control form-control-sm'}}) }}
        				</div>
        			</div>
        		</div>
        	</div>
        	<!-- ========================================================================================= -->
           	<!-- =========================== D A T E   D E P A R T   ===================================== -->
        	<div style="border-bottom:1px solid #AAAAAA; margin-top:20px;" class="row">
        		<h3 class="col-6">Date de départ</h3>
        	</div>
        	<div style="margin-top:10px;" class="row">
        		<div class="offset-1 col-10">
{#         			<div class="row">#}
        		        {{ form_widget(formEvent.dateStart, {'attr' : {'class':'row'}}) }}
{#         		    </div>#}
        		</div>
        	</div>
        	<div style="border-bottom:1px solid #AAAAAA; margin-top:20px;" class="row">
        		<h3 class="col-6">Fin</h3>
        	</div>
        	<div style="margin-top:10px;" class="row">
           		<button type="submit" class="btn btn-secondary btn-sm" style="margin-bottom:30px">Enregistrer l'évenement</button>
           	</div>
        {{ form_end(formEvent) }}
    </div>
   
    <script src="{{ asset('bootstrap/Js/jquery.js') }}"></script>
    <script src="{{ asset('Js/Ajaxreceive.js') }}"></script>
    <script>
        var $addTagButton = $('#buttonAdd');					//Bouton +UsersId
        var $addMachineButton = $('#buttonAddMachine');
        var $newLinkLiUser = $('<li name="user"></li>');//.append($addTagButton);
        var $newLinkLiMachine = $('<li name="mach"></li>');
        var lastUserId;
        var $collectionHolder;
        var lastUserSelect, lastUserSelected;
        var allUserInput = [];

        jQuery(document).ready(function() {
            $collectionHolder = $('ul#listeUserId');									//On récupère dans la page la balise <ul> avec la class : listeUserId
            $collectionHolderMachine = $('ul.listeMachineId');	
            $collectionHolder.append($newLinkLiUser);										//On ajoute un nouveau <li></li>
            $collectionHolderMachine.append($newLinkLiMachine);								//On ajoute un nouveau <li></li>
            $collectionHolder.data('index', $collectionHolder.find(':input').length);	//La donnée 'index' = nombre de select 
            $collectionHolderMachine.data('index', $collectionHolder.find(':input').length);	//La donnée 'index' = nombre de select
            addTagForm($collectionHolder, $newLinkLiUser);									//Au chargement de la page on ajoute un champ select user
			$addMachineButton.on('click', function(){
				addMachineForm($collectionHolderMachine, $newLinkLiMachine);
			});
			$('#new_event_form_machinesid').parent().remove();
			$('#new_event_form_usersid').parent().remove();
			$('#new_event_form_dateStart select').each(function(){
					$(this).addClass('form-control form-control-sm col-4');
				});
        });
        function addTagForm($collectionHolder, $newLinkLiUser)
        {
            var prototype = $collectionHolder.data('prototype');						//On recuprere le data-prototype.
            var index = $collectionHolder.data('index');								//On recupere l'index (nombre de select)
			lastUserSelected = '#new_event_form_usersid_' + index + '_user';			//Var contenant l'id du nouveau <select>
			lastUserSelected2 = '#new_event_form_usersid_' + (index-1) + '_user';		//Var contenant l'id du <select> précedent
			//allUserInput.push(lastUserSelected);										//Tableau contenant tout les id des select
			$(lastUserSelected2).off();													//On désactive les events sur le champ précédent
            var newForm = prototype;

            //Ajout boutton delete sur l'ancien UserSelect;
            var last = $(lastUserSelected2).parent();//.parent().parent().parent();
            $(last).addClass( "row" );
//             $(last).parent().parent().parent().parent().css("margin-top","20px");
            $(last).append('<span class="col-1" onclick="DeleteLi('+'\'#new_event_form_usersid_'+(index-1)+'_user'+'\');" style="cursor: pointer;"><i class="fas fa-times-circle" style="color:#EE8686"></i></span>');
            
            // You need this only if you didn't set 'label' => false in your tags field in TaskType
            // Replace '__name__label__' in the prototype's HTML to
            // instead be a number based on how many items we have
            // newForm = newForm.replace(/__name__label__/g, index);

            // Replace '__name__' in the prototype's HTML to
            // instead be a number based on how many items we have
            newForm = newForm.replace(/__name__/g, index);

            // increase the index with one for the next item
            $collectionHolder.data('index', index + 1);

            // Display the form in the page in an li, before the "Add a tag" link li
            var $newFormLi = $('<li></li>').append(newForm);
//             $newFormLi.append('<span onclick="console.log(\'click delete\');" style="cursor: pointer;"><i class="fas fa-times-circle" style="color:#EE8686"></i></span>');
			$newLinkLiUser.before($newFormLi);
			$(lastUserSelected).addClass( "form-control form-control-sm col-11" );	
			
			var label = $('label[for='+lastUserSelected.split('#')[1] +']')
			label.remove();
			$(lastUserSelected).change(function(){				//On créer un evenement sur le champs actuel
				addTagForm($collectionHolder, $newLinkLiUser);
				})
            }
        	function addMachineForm($collectionHolderMachine, $newLinkLiMachine)
        	{
        		var prototype = $collectionHolderMachine.data('prototype');
        	    var index = $collectionHolderMachine.data('index');
        	    var newForm = prototype;
        	    newForm = newForm.replace(/__name__/g, index);

        	    // increase the index with one for the next item
        	    $collectionHolderMachine.data('index', index + 1);

        	    // Display the form in the page in an li, before the "Add a tag" link li
        	    var $newFormLi = $('<li></li>').append(newForm);
        	    $newLinkLiMachine.before($newFormLi);
        	    var idForm = '#new_event_form_machinesid_'+index+'_ModeleMachine';
        	    var idFormMach = '#new_event_form_machinesid_'+index+'_maintenancesDispo';
        	    var idFormMachine = '#new_event_form_machinesid_'+index+'_machinesDispo';
				var $formActual = $('#new_event_form_machinesid_'+index+'_ModeleMachine');
        	    $(idForm).addClass("form-control form-control-sm");
        	    $(idFormMach).addClass("form-control form-control-sm");
        	    $(idFormMachine).addClass("form-control form-control-sm");
        	    $(idForm).parent().parent().parent().parent().css('border','1px solid #AAAAAA');
        	    $(idForm).parent().parent().parent().parent().append('<span class="col-1" onclick="DeleteLi('+'\'#new_event_form_machinesid_'+index+'_ModeleMachine'+'\');" style="cursor: pointer;"><i class="fas fa-times-circle" style="color:#EE8686"></i></span>');
				console.log(idForm, $formActual);
				$formActual.change(function(){
					var $form = $(this).closest('form');
					var data = {};
					data[$formActual.attr('name')] = $formActual.val();
					console.log(data, $formActual.val());
						$.ajax({
						url  : $form.attr('action'),
						type : $form.attr('method'),
						data : data,
						success: function(html){
							console.log('SUCCESS !!');
							$('#new_event_form_machinesid_'+index+'_maintenancesDispo').replaceWith(
								$(html).find(('#new_event_form_machinesid_'+index+'_maintenancesDispo'))
								);
							$('#new_event_form_machinesid_'+index+'_maintenancesDispo').addClass("form-control form-control-sm");
							$('#new_event_form_machinesid_'+index+'_machinesDispo').replaceWith(
									$(html).find(('#new_event_form_machinesid_'+index+'_machinesDispo'))
									);
								$('#new_event_form_machinesid_'+index+'_machinesDispo').addClass("form-control form-control-sm");
							}
						
						});
					});
        	    
            }
            function DeleteLi(id)
            {
				$(id).parent().parent().parent().parent().remove();
            }
    </script>
{% endblock %}